# This workflow runs some tests to make sure everything's fine before introducing bad code or a bug into the production website
name: Continuous Integration

on: push

# Cancel previous instances of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint # This "lints" our entire project, making sure the code is correct, conforms to our style and isn't poorly written
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
            - name: Setup
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 16 # Use the latest LTS release
                  cache: npm
            - name: Install
              uses: nick-fields/retry@v2.6.0 # Retry npm installation when an http download fails (often due to rate limiting)
              with:
                  timeout_minutes: 5
                  max_attempts: 3
                  command: npm ci # Installs dependencies without modifying lockfile (for production installs)
                  retry_wait_seconds: 60
            - name: Run Linters
              run: npm run lint
              env:
                  ci: true
                  NODE_ENV: production
    typecheck:
        name: Type Checking # TypeScript checks the static typings in our code
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
            - name: Setup
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 16 # Use the latest LTS release
                  cache: npm
            - name: Install
              uses: nick-fields/retry@v2.6.0 # Retry npm installation when an http download fails (often due to rate limiting)
              with:
                  timeout_minutes: 5
                  max_attempts: 3
                  command: npm ci # Installs dependencies without modifying lockfile (for production installs)
                  retry_wait_seconds: 60
            - name: Run TypeScript
              run: npm run check
              env:
                  ci: true
                  NODE_ENV: production
