# This workflow makes sure that only stargazers can litter the repo with issues
name: Issue opened

on:
    issues:
        types:
            - opened
            - transferred
            - reopened

# Cancel previous instances of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    drip_check:
        name: Drip Check
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: (!contains(fromJson('["dependabot[bot]", "renovate[bot]"]'), github.event.issue.user.login))
        steps:
            - name: Gimme! Gimme! Gimme! (A Star After Midnight) # closes if you didn't pass the drip check
              uses: uhyo/please-star-first@v1.0.1
